name: Deploy to neocities

# only run on changes to master
on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    - run: |
        mkdir public/
    - name: Build Eleventy (11ty)
      uses: TartanLlama/actions-eleventy@v1.3
      with:
        install_dependencies: true
        args: --input src/. --output=public/ --config=.eleventy.js
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public
